baseURL = "https://example.org/"
languageCode = "en-us"
title = "AlanWu's Site"
# 主题以模块形式引入，不再使用 theme = "ananke"

[caches]
  [caches.images]
    dir = ":cacheDir/images"


theme = "docsy"

disableGitInfo = true



[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  # 可选：若本地开发 Docsy，可使用 workspace
  # workspace = "docsy.work"

# 全局参数配置
[params]
  # Light/Dark 模式切换按钮
  [params.ui]
    showLightDarkModeMenu = true
    # navbar 透明效果关闭可如下配置
    # navbar_translucent_over_cover_disable = true

  # 版本切换下拉菜单
  version_menu = "版本"
  [[params.versions]]
    version = "latest"
    url     = "https://example.org"
  [[params.versions]]
    version = "v1.0"
    url     = "https://v1.example.org"

# 高亮代码设置与 Markdown 渲染
[markup]
  [markup.highlight]
    style      = "tango"
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# 可选：若要集成 Google Custom Search
# gcs_engine_id = "你的搜索引擎ID"

# 当前未设置多语言结构，可考虑添加以下节
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params.custom]
coverImageFull = "https://api.fungit.org/covers.php"
coverImageSmall = "https://api.fungit.org/covers.php?type=small"

